pipeline:
  name: DemoMohits
  identifier: DemoMohit
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: svc22
          environment:
            environmentRef: env1
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infra1
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo '<+configFile.getAsString("/test")>'
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10m
            rollbackSteps:
              - step:
                  type: Wait
                  name: Wait_2
                  identifier: Wait_2
                  spec:
                    duration: 10m
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  projectIdentifier: sahiltest
  orgIdentifier: default
