pipeline:
  name: sahil-test
  identifier: sahiltest
  projectIdentifier: sahiltest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: ShellScript_1
                  identifier: ShellScript_1
                  template:
                    templateRef: tname
                    versionLabel: V1
        tags: {}
